### ISSUE TITLE
npm start fails with "SyntaxError: Unexpected token"

### ISSUE THREAD

**Issue by lvzon** [derXge/whatsappsaver#1]
I attempted to run whatsappsaver on two different systems, both running variants of Ubuntu Linux, but I get an "Unexpected token" error:

```
~/src/whatsappsaver$ npm install

> protobufjs@6.11.2 postinstall /home/levien/src/whatsappsaver/node_modules/protobufjs
> node scripts/postinstall

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN whatsappsaver@1.0.0 No repository field.
npm WARN whatsappsaver@1.0.0 license should be a valid SPDX license expression

added 175 packages from 194 contributors and audited 175 packages in 14.892s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

~/src/whatsappsaver$ npm start

> whatsappsaver@1.0.0 start /home/levien/src/whatsappsaver
> node index.js

/home/levien/src/whatsappsaver/systems/baileysSystem.js:34
     allChats       = client?.chats?.array,
                             ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/levien/src/whatsappsaver/index.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsappsaver@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the whatsappsaver@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/levien/.npm/_logs/2021-11-29T20_01_53_887Z-debug.log
```

This is the contents of the debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle whatsappsaver@1.0.0~prestart: whatsappsaver@1.0.0
6 info lifecycle whatsappsaver@1.0.0~start: whatsappsaver@1.0.0
7 verbose lifecycle whatsappsaver@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle whatsappsaver@1.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/levien/src/whatsappsaver/node_modules/.bin:/home/levien/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle whatsappsaver@1.0.0~start: CWD: /home/levien/src/whatsappsaver
10 silly lifecycle whatsappsaver@1.0.0~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle whatsappsaver@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle whatsappsaver@1.0.0~start: Failed to exec start script
13 verbose stack Error: whatsappsaver@1.0.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid whatsappsaver@1.0.0
15 verbose cwd /home/levien/src/whatsappsaver
16 verbose Linux 5.11.0-37-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error whatsappsaver@1.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the whatsappsaver@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by xgedev** [comment]
Hey, it looks like your NodeJS / NPM version is outdated (v10 instead of v17). You can download the newest one here: https://nodejs.org/en/download/.

**Comment by lvzon** [comment]
You're absolutely right, it seems the NodeJS-version in the Ubuntu LTS repositories is quite outdated.
I did an upgrade to v17 using the instructions here: https://github.com/nodesource/distributions
Now it does at least start. I do still get an error, but that could be because I joined the new beta API...
Perhaps it's good to add a minimum required NodeJS version to the documentation?

The error I get now is:

```
INFO [2021-11-30 13:30:35.762 +0000] (294698): validated connection successfully
    class: "Baileys"
INFO [2021-11-30 13:30:35.766 +0000] (294698): opened connection to WhatsApp Web
    class: "Baileys"
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/home/levien/src/whatsappsaver/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/home/levien/src/whatsappsaver/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/home/levien/src/whatsappsaver/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:86:18)
    at WAConnection.emit (node:events:390:28)
    at WAConnection.emit (/home/levien/src/whatsappsaver/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v17.1.0
```

**Comment by xgedev** [comment]
Okay, nice that it starts now!
What do you mean by _you joined the new beta API_?
Unfortunately, I don't use WhatsApp anymore but I still get to the point where you need to scan the QR code to continue backuping, could you already scan it?

And I added the minimum requirement to the package.json now, thanks for the suggestion!

**Comment by lvzon** [comment]
I meant that I activated Whatsapp's new multi-device beta: https://faq.whatsapp.com/general/download-and-installation/about-multi-device-beta
I was able to scan the QR-code, but then I got the `TypeError [ERR_INVALID_ARG_TYPE]`. Not sure if that's related to the beta or whether I have another outdated component somewhere... (I haven't tried disabling the beta feature yet.)

**Comment by xgedev** [comment]
I just updated the package.json so that the exact version(s) of the libraries I used are downloaded.
Completely delete your locally installed files and download it again, maybe it works now :)

**Comment by lvzon** [comment]
That did change the behaviour again, indeed. I tried on two different machines, I get QR-codes again but can't scan them (although the look better in my terminal compared to github's formatting below), and the same error keeps repeating.

```
INFO [2021-12-02 10:51:26.056 +0000] (13297): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▄▄▄ ▀▀▀▄▀█  █▄██ █ ▄▄▄▄▄ █
█ █   █ ██▄▀ █ ▄ ▄▀▀ ▀  █▄█ █   █ █
█ █▄▄▄█ ██▀▄ ▄█▀▄ ▀█▄▀█ ▀▀█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ ▀▄█ ▀ ▀▄█▄█▄█ ▀▄█▄▄▄▄▄▄▄█
█▄ █▄ █▄▀▀▄▀█▄▄ ▄▄  ▄▄ █▄▄█▄▀▀█▀█ █
██▄▄▀▄▄▄▄█▄██▄█ ▄▀ ▀▀▄▄█▄ ▀█▀ ▄▀  █
█▄█▀▄  ▄ ▄  █▀▀▄█ █▄▄█ █▀█▄▄▀▄ ▄▀██
█ ▄ ▀ ▄▄▀▀▀██▀▄▀ ▀██▄▄█▀▀▀▄▀██▀ ▀██
█▄██▄▀▀▄██▄█ ▄█▀  █▀█▀▀▄▄▄▄▄  ▀▄▀ █
█ █▀█▀▀▄▄▀▄█▀▄▀▄▄▄▄  █▄   ▀▀ █▀ █▄█
█▀▀▀▄▀ ▄█▄ ▀▄ ▀▄ █▄▀▄▄██▀█▀█▀▀ ▀ ██
█ █▀▄▄█▄▄█▀▄ ██ ▄▀ ▄█▀█▀▄ █▀▄█  ▄▄█
█▄▄█▄██▄▄ ▄▄▀▀ ▀▀█▄▀▄▄▀██ ▄▄▄ ▄█▀██
█ ▄▄▄▄▄ ██ ▀██▄▄▄▄█▄  █▄  █▄█ ▄▀▄██
█ █   █ █ ▀▄█▀▀█▀█▀▄▀▀▄    ▄ ▄█▀▄▄█
█ █▄▄▄█ █▀▀▀▄▀▀█ ▄▄▀  ▄█ ▄█ ▄ ▀▀▀ █
█▄▄▄▄▄▄▄█▄▄███▄▄█▄▄█▄▄▄██▄██▄▄█▄███

WARN [2021-12-02 10:51:26.178 +0000] (13297): connect attempt 8 failed: Error: close, retrying...
    class: "Baileys"
    error: {}
```
Maybe this is related to the beta? :) It can no longer be a version issue, I guess...
I'll probably try to disable the beta again when I get round to it, to test what happens.

**Comment by lvzon** [comment]
I just disabled the beta, and it didn't change the error, so I guess it's caused by something else... Scanning the Whatsapp Web QR-code works, but the one in the terminal won't scan, and the application exits after 10 retries:

```
INFO [2021-12-06 23:45:56.071 +0000] (16126): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▄▄██████ █▀▄▄   ██ ▄▄▄▄▄ █
█ █   █ █ ▀█ ▄ ▄█▄▀ █▀▀ ███ █   █ █
█ █▄▄▄█ █▄ ▄▄▀█▀█▄█ ▀▀▀██▀█ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄▀▄▀▄█▄▀▄▀ █ █ ▀▄█▄▄▄▄▄▄▄█
█▄▄ ▄▀█▄█▄▀███ ▄▀▀ ▀   ▀▀█▄██▄  █ █
█▄ ▄▀▀▄▄▄▀██▀▀  ██▄▄▀██▄ ▄▄▀█ ▀▄▄ █
██ ▀▄██▄▄█▄▀ ██▄▄▀▄█ █▀▀▄ ▄█ █▀▀▀██
█▀█▄█▄ ▄ ▀ ██ █▀█▀▄  ▄▀▄█▄▀ ▀ ▄ █▀█
█▀█▄  ▀▄▀█▀█▄▀▄█▀█▀▄  ▄▄ ▄▄▄▀▀▀▄ ▀█
█▀ █ ▀█▄▀▄▄▀▄ █▄ █ ██▄█ ▀  ▀█▀▄█▄██
█ ▀▄█▄█▄▀▄█▀▄▀█▀▀  ▀▀▀   █▀▀ █▀▀▀██
██▀▄█▄ ▄▄▀█ ▄ ▀▄▀▄█▀▀▄▄  █▀ ██▀▄ ▄█
█▄█▄▄▄█▄█▀  ▄█▄█▄▀ █▄▄█ ▀ ▄▄▄ ██▄▄█
█ ▄▄▄▄▄ █████▄▄█▀▀▄ ▄█  ▀ █▄█ ▀▀▄▀█
█ █   █ █▀▀ ▀▄████ ▄▀▀   ▄▄▄ ▄██ ▄█
█ █▄▄▄█ █ ▀▄▀███▄█▀▀▀▄██▀██▀▄▀▀█▄▀█
█▄▄▄▄▄▄▄█▄▄██▄▄▄███▄▄▄▄▄▄██▄█▄▄▄███

WARN [2021-12-06 23:45:56.175 +0000] (16126): connect attempt 10 failed: Error: close
    class: "Baileys"
    error: {}
INFO [2021-12-06 23:45:56.175 +0000] (16126): closed connection, reason close
    class: "Baileys"
/media/levien/extdata/levien/src/whatsappsaver/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:119
            this.conn.on('close', () => rejectAll(new Error(Constants_1.DisconnectReason.close)));
                                                  ^

Error: close
    at WebSocket.<anonymous> (/media/levien/extdata/levien/src/whatsappsaver/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:119:51)
    at WebSocket.emit (node:events:390:28)
    at WebSocket.emitClose (/media/levien/extdata/levien/src/whatsappsaver/node_modules/ws/lib/websocket.js:246:10)
    at TLSSocket.socketOnClose (/media/levien/extdata/levien/src/whatsappsaver/node_modules/ws/lib/websocket.js:1088:15)
    at TLSSocket.emit (node:events:402:35)
    at node:net:687:12
    at TCP.done (node:_tls_wrap:580:7)

Node.js v17.2.0
``` 

The problem seems to be with Baileys, because if I change its version from "3.5.0" to ">3.5.0" in package.json, it does work! I'm now using it with Baileys 3.5.3, perhaps 3.5.0 doesn't work anymore with the current Whatsapp-version?

**Comment by xgedev** [comment]
Oh, so you fixed it by changing Baileys to v3.5.3?
Maybe WhatsApp changed something in their API then..

**Comment by lvzon** [comment]
Yes, it seems that specifying 3.5.3 rather than 3.5.0 in package.json fixes the remaining problem... It probably won't work with the multi-device beta though, because that requires a separate version of Baileys with a slightly different API. But at least I was able to make a full backup. :)

**Comment by xgedev** [comment]
That's great! I updated the Baileys version to 3.5.3 now, thank you!
